export const BOOKING_STATUS = {
  REQUEST_SENT: "REQUEST_SENT",
  WORKER_REVIEWING: "WORKER_REVIEWING",
  WORKER_INTERESTED: "WORKER_INTERESTED",
  CUSTOMER_CONFIRMATION_PENDING: "CUSTOMER_CONFIRMATION_PENDING",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  WORKER_ACCEPTED: "WORKER_ACCEPTED",
  ON_THE_WAY: "ON_THE_WAY",
  ARRIVED: "ARRIVED",
  OTP_VERIFIED: "OTP_VERIFIED",
  SERVICE_STARTED: "SERVICE_STARTED",
  SERVICE_COMPLETED: "SERVICE_COMPLETED",
  BILL_GENERATED: "BILL_GENERATED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export type BookingStatusConstant = (typeof BOOKING_STATUS)[keyof typeof BOOKING_STATUS];
