export const PRICING_TYPES = {
  PLATFORM_ESTIMATE: "PLATFORM_ESTIMATE",
  WORKER_ESTIMATE: "WORKER_ESTIMATE",
  FINAL_BILL: "FINAL_BILL",
  MINIMUM_SERVICE_VISIT_CHARGE: "MINIMUM_SERVICE_VISIT_CHARGE",
} as const;

export type PricingTypeConstant = (typeof PRICING_TYPES)[keyof typeof PRICING_TYPES];
