/**
 * Isolated development & seed presentation data for Worker Task 1.
 * 
 * NOTE: These mock fixtures provide UI presentation data where backend integration
 * is not yet seeded. Once backend endpoints become available in Tasks 2 & 3,
 * these structures will transition to live services.
 */

import type {
  WorkerIdentity,
  WorkerOverviewStats,
  WorkerJobRequest,
  WorkerScheduleItem,
  WorkerProfileDetails,
  WorkerEarningsSummary,
  WorkerEarningsRecord,
  WorkerWelfareDetails,
} from "../types";

export const DEMO_WORKER_IDENTITY: WorkerIdentity = {
  name: "Ravi Patel",
  trade: "Plumber",
  cooperativeName: "ABC Labour Cooperative Society",
  cooperativeRole: "Member • Verified Worker",
  federationName: "Gujarat Labour Cooperative Federation",
  location: "Ahmedabad, Gujarat",
  rating: 4.8,
  reviewsCount: 342,
  isVerified: true,
};

export const DEMO_WORKER_OVERVIEW_STATS: WorkerOverviewStats = {
  todaysJobs: 3,
  todaysEarnings: 1850,
  overallRating: 4.8,
  completedJobs: 342,
};

export const DEMO_JOB_REQUESTS: WorkerJobRequest[] = [
  {
    id: "req-101",
    bookingNumber: "BK-GJ-2026-0812",
    serviceTitle: "Main Water Line Leakage Repair",
    categoryName: "Plumbing",
    customerName: "Rahul Sharma",
    customerArea: "Satellite, Ahmedabad",
    distanceKm: 2.1,
    scheduledDate: "Today",
    scheduledTime: "4:00 PM",
    scheduledStartAt: "TodayT16:00:00",
    problemDescription: "Urgent pressure pipe rupture in residential ground floor pipeline. Requires pipe clamp and sealant replacement.",
    totalAmount: 790,
    estimatedPayout: 750,
    workerEarnings: 750,
    status: "REQUEST_SENT",
    urgency: "EMERGENCY",
    cooperativeName: "ABC Labour Cooperative Society",
    timeSlot: "Immediate / Within 1 hour",
    description: "Urgent pressure pipe rupture in residential ground floor pipeline. Requires pipe clamp and sealant replacement.",
    cooperativeSociety: "ABC Labour Cooperative Society",
    createdAt: "10 mins ago",
  },
  {
    id: "req-102",
    bookingNumber: "BK-GJ-2026-0815",
    serviceTitle: "Dual Bathroom Fixture Replacement",
    categoryName: "Plumbing",
    customerName: "Neha Mehta",
    customerArea: "Vastrapur, Ahmedabad",
    distanceKm: 3.4,
    scheduledDate: "Today",
    scheduledTime: "5:30 PM",
    scheduledStartAt: "TodayT17:30:00",
    problemDescription: "Installation of two mixer taps and flush valve assembly. Customer has provided replacement fittings.",
    totalAmount: 1160,
    estimatedPayout: 1100,
    workerEarnings: 1100,
    status: "REQUEST_SENT",
    urgency: "STANDARD",
    cooperativeName: "ABC Labour Cooperative Society",
    timeSlot: "Today, 3:30 PM - 5:30 PM",
    description: "Installation of two mixer taps and flush valve assembly. Customer has provided replacement fittings.",
    cooperativeSociety: "ABC Labour Cooperative Society",
    createdAt: "35 mins ago",
  },
];

export const DEMO_TODAY_SCHEDULE: WorkerScheduleItem[] = [
  {
    id: "sch-1",
    time: "10:00 AM",
    serviceTitle: "Electrical Repair",
    status: "Upcoming",
    customerName: "Sanjay Joshi",
    customerArea: "Bodakdev, Ahmedabad",
    estimatedDuration: "1.5 hours",
    notes: "Main breaker tripping inspection and socket replacement.",
  },
  {
    id: "sch-2",
    time: "2:00 PM",
    serviceTitle: "Pipe Repair",
    status: "Confirmed",
    customerName: "Meera Trivedi",
    customerArea: "Navrangpura, Ahmedabad",
    estimatedDuration: "2 hours",
    notes: "Sink drainage blockage clearing and trap replacement.",
  },
  {
    id: "sch-3",
    time: "5:00 PM",
    serviceTitle: "Maintenance",
    status: "Upcoming",
    customerName: "Amit Shah",
    customerArea: "Paldi, Ahmedabad",
    estimatedDuration: "1 hour",
    notes: "Routine quarterly valve and overhead tank check.",
  },
];

export const DEMO_WORKER_PROFILE: WorkerProfileDetails = {
  name: "Ravi Patel",
  trade: "Plumber",
  rating: 4.8,
  reviewsCount: 342,
  experienceYears: 7,
  cooperativeName: "ABC Labour Cooperative Society",
  cooperativeId: "COOP-GJ-AHM-041",
  federationName: "Gujarat Labour Cooperative Federation",
  location: "Ahmedabad, Gujarat",
  phone: "+91 98250 11021",
  languages: ["Gujarati", "Hindi", "English"],
  skills: [
    "Pipe Repair",
    "Leakage Repair",
    "Bathroom Plumbing",
    "Water Tank Maintenance",
  ],
  verifications: {
    identity: true,
    phone: true,
    worker: true,
    skill: true,
  },
  hourlyRate: 350,
  bio: "Certified master plumber with 7+ years of experience across residential and commercial plumbing installations in Ahmedabad. Dedicated cooperative member committed to transparent pricing and reliable workmanship.",
};

export const DEMO_EARNINGS_SUMMARY: WorkerEarningsSummary = {
  todaysEarnings: 1850,
  thisWeekEarnings: 9400,
  thisMonthEarnings: 38250,
  completedJobsCount: 342,
  bankName: "State Bank of India (Cooperative Payroll Account)",
  accountEnding: "4129",
  ifscPrefix: "SBIN0001234",
  nextPayoutTime: "Today at 6:00 PM",
};

export const DEMO_EARNINGS_RECORDS: WorkerEarningsRecord[] = [
  {
    id: "ern-1",
    bookingNumber: "BK-GJ-2026-0798",
    serviceTitle: "Overhead Tank Valve Replacement",
    date: "Today, Sep 3",
    time: "11:30 AM",
    customerArea: "Satellite, Ahmedabad",
    grossAmount: 950,
    welfareCess: 50,
    netPayout: 900,
    status: "Transferred",
    referenceId: "TXN-GJ-9021-01",
  },
  {
    id: "ern-2",
    bookingNumber: "BK-GJ-2026-0785",
    serviceTitle: "Kitchen Sink Trap Clearance",
    date: "Today, Sep 3",
    time: "08:45 AM",
    customerArea: "Vastrapur, Ahmedabad",
    grossAmount: 1000,
    welfareCess: 50,
    netPayout: 950,
    status: "Transferred",
    referenceId: "TXN-GJ-9021-02",
  },
  {
    id: "ern-3",
    bookingNumber: "BK-GJ-2026-0761",
    serviceTitle: "Emergency Bathroom Pipe Sealant",
    date: "Sep 2, 2026",
    time: "04:15 PM",
    customerArea: "Bodakdev, Ahmedabad",
    grossAmount: 1250,
    welfareCess: 50,
    netPayout: 1200,
    status: "Transferred",
    referenceId: "TXN-GJ-8994-01",
  },
  {
    id: "ern-4",
    bookingNumber: "BK-GJ-2026-0740",
    serviceTitle: "Shower Panel Fixture Repair",
    date: "Sep 2, 2026",
    time: "11:00 AM",
    customerArea: "Navrangpura, Ahmedabad",
    grossAmount: 850,
    welfareCess: 50,
    netPayout: 800,
    status: "Transferred",
    referenceId: "TXN-GJ-8994-02",
  },
  {
    id: "ern-5",
    bookingNumber: "BK-GJ-2026-0711",
    serviceTitle: "Water Meter Pipe Installation",
    date: "Sep 1, 2026",
    time: "02:30 PM",
    customerArea: "Thaltej, Ahmedabad",
    grossAmount: 1600,
    welfareCess: 80,
    netPayout: 1520,
    status: "Transferred",
    referenceId: "TXN-GJ-8971-01",
  },
];

export const DEMO_WELFARE_DETAILS: WorkerWelfareDetails = {
  insuranceStatus: "Active",
  policyNumber: "POL-GJ-2026-9081",
  providerName: "Gujarat Labour Cooperative Welfare & Health Mutual",
  coverageAmount: 500000,
  welfareSchemeStatus: "Enrolled",
  emergencyAssistanceStatus: "Eligible",
  benefits: [
    {
      title: "Accident Coverage",
      description: "24/7 comprehensive on-duty and transit accidental coverage up to ₹5,00,000 with cashless hospital network.",
    },
    {
      title: "Emergency Support",
      description: "Instant cooperative welfare grant assistance for family medical emergencies and specialized surgical interventions.",
    },
    {
      title: "Training Programs",
      description: "Quarterly government-accredited skill upgrades, advanced tooling subsidies, and safety refresher modules.",
    },
  ],
  certifications: [
    {
      id: "cert-1",
      title: "Plumbing Certification",
      status: "Verified",
      validityText: "Valid until December 2027",
      issuedBy: "National Skill Development Corporation (NSDC) & Gujarat Federation",
      certCode: "CERT-PL-GJ-8842",
    },
    {
      id: "cert-2",
      title: "Safety Training",
      status: "Completed",
      validityText: "Completed — Annual certification current",
      issuedBy: "Gujarat State Labour Welfare Board",
      certCode: "SAFE-TR-2026-09",
    },
    {
      id: "cert-3",
      title: "First Aid Training",
      status: "Completed",
      validityText: "Completed — Red Cross Cooperative Chapter",
      issuedBy: "Indian Red Cross Society & Labour Federation",
      certCode: "FA-COOP-2026-114",
    },
  ],
  expiringWarning: {
    certName: "Electrical Safety Certificate",
    daysRemaining: 30,
  },
};
